---
- name: Eksecute autPurge.sh.
  hosts: nvr
  tasks:
     - name: Execute the script
       command: sh /home/test_user/test.sh
       
     - name: Display the config
       ansible.builtin.debug:
         msg: "Config displayed"
