---
- name: Manpurge nvr KAG
  hosts: nvr
  tasks:
    - name: Transfer bash file to host
      ansible.builtin.copy:
        src: /ansible_unifi_authpuRge/authPurge.sh
        dest: /bin/autPurge.sh
        force: yes

    - name: Display the config
      ansible.builtin.debug:
        msg: "Config displayed"

